// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GdAZ7A5pDwDNpcRnMLSTWKxaiGhs6nc',
    appId: '1:1023252264693:web:0f17700f70891e52a7b7bc',
    messagingSenderId: '1023252264693',
    projectId: 'chat-app-aac3c',
    authDomain: 'chat-app-aac3c.firebaseapp.com',
    storageBucket: 'chat-app-aac3c.firebasestorage.app',
    measurementId: 'G-7XNX418SY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1bdsnUHGWDo52d7AR5CXfS6Lo6K0qbaY',
    appId: '1:1023252264693:android:c55f9b7b02e8180ca7b7bc',
    messagingSenderId: '1023252264693',
    projectId: 'chat-app-aac3c',
    storageBucket: 'chat-app-aac3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3W3CfugomuiFePWtGa1uGQnhB_dYX7xY',
    appId: '1:1023252264693:ios:121ed57be5d65a88a7b7bc',
    messagingSenderId: '1023252264693',
    projectId: 'chat-app-aac3c',
    storageBucket: 'chat-app-aac3c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3W3CfugomuiFePWtGa1uGQnhB_dYX7xY',
    appId: '1:1023252264693:ios:121ed57be5d65a88a7b7bc',
    messagingSenderId: '1023252264693',
    projectId: 'chat-app-aac3c',
    storageBucket: 'chat-app-aac3c.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0GdAZ7A5pDwDNpcRnMLSTWKxaiGhs6nc',
    appId: '1:1023252264693:web:07928d8604143041a7b7bc',
    messagingSenderId: '1023252264693',
    projectId: 'chat-app-aac3c',
    authDomain: 'chat-app-aac3c.firebaseapp.com',
    storageBucket: 'chat-app-aac3c.firebasestorage.app',
    measurementId: 'G-F01T6C9TJQ',
  );

}